# Generated by Django 5.0.3 on 2024-05-06 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0005_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="case_shape",
        ),
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="product",
            name="glass_feature",
        ),
        migrations.RemoveField(
            model_name="product",
            name="mechanism",
        ),
        migrations.RemoveField(
            model_name="product",
            name="strap_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tarz",
        ),
        migrations.AddField(
            model_name="product",
            name="favori",
            field=models.ManyToManyField(
                related_name="FavoriyeEkleyenler",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Favoriye ekleyenler",
            ),
        ),
        migrations.DeleteModel(
            name="CaseShape",
        ),
        migrations.DeleteModel(
            name="Color",
        ),
        migrations.DeleteModel(
            name="Gender",
        ),
        migrations.DeleteModel(
            name="GlassFeature",
        ),
        migrations.DeleteModel(
            name="Mechanism",
        ),
        migrations.DeleteModel(
            name="StrapType",
        ),
        migrations.DeleteModel(
            name="Style",
        ),
    ]
