# Generated by Django 5.0.3 on 2024-05-08 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "AppEcommerce",
            "0006_remove_product_case_shape_remove_product_color_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
