# Generated by Django 5.0.3 on 2024-05-11 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0007_delete_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name_plural": "EV tipi"},
        ),
        migrations.RemoveField(
            model_name="brand",
            name="image",
        ),
    ]
