# Generated by Django 5.0.3 on 2024-05-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0009_remove_product_model_remove_product_model_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="room_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
