# Generated by Django 5.0.3 on 2024-05-12 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0010_alter_product_room_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
    ]
