# Generated by Django 5.0.3 on 2024-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0012_delete_brand_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="room_number",
            field=models.CharField(
                choices=[
                    ("1+1", "1+1"),
                    ("2+1", "2+1"),
                    ("3+1", "3+1"),
                    ("4+1", "4+1"),
                    ("5+1", "5+1"),
                    ("6+1", "6+1"),
                    ("7+1", "7+1"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
