# Generated by Django 5.0.3 on 2024-05-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0013_alter_product_room_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="konum",
            field=models.TextField(null=True),
        ),
    ]
