# Generated by Django 5.0.3 on 2024-05-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0019_alter_product_image_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.CharField(
                choices=[("istanbul", "istanbul"), ("ankara", "ankara")],
                max_length=50,
                null=True,
            ),
        ),
    ]
