# Generated by Django 5.0.3 on 2024-05-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0020_alter_product_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="adres",
            field=models.TextField(null=True),
        ),
    ]
