# Generated by Django 5.0.3 on 2024-05-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0022_product_metre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
