# Generated by Django 5.0.3 on 2024-06-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0024_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="havuz",
            field=models.BooleanField(null=True),
        ),
    ]
