# Generated by Django 5.0.3 on 2024-06-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0025_product_havuz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                choices=[("Building", "Building"), ("müstakil", "Detached")],
                max_length=50,
                null=True,
            ),
        ),
    ]
