# Generated by Django 5.0.3 on 2024-06-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0027_alter_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                choices=[("Building", "Building"), ("Detached", "Detached")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="durum",
            field=models.CharField(
                choices=[("Rent", "Rent"), ("Sale", "Sale")], max_length=50, null=True
            ),
        ),
    ]
