# Generated by Django 5.0.3 on 2024-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0029_alter_product_brand_alter_product_durum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.CharField(
                choices=[("istanbul", "İstanbul"), ("ankara", "Ankara")],
                max_length=50,
                null=True,
            ),
        ),
    ]
