# Generated by Django 5.0.3 on 2024-06-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0030_alter_product_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.CharField(
                choices=[("İstanbul", "istanbul"), ("Ankara", "ankara")],
                max_length=50,
                null=True,
            ),
        ),
    ]
