# Generated by Django 5.0.3 on 2024-06-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0031_alter_product_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                choices=[("bina", "Building"), ("müstakil", "Detached")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="durum",
            field=models.CharField(
                choices=[("kiralık", "Rent"), ("satılık", "Sale")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.CharField(
                choices=[("istanbul", "İstanbul"), ("ankara", "Ankara")],
                max_length=50,
                null=True,
            ),
        ),
    ]
