# Generated by Django 5.0.3 on 2024-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0032_alter_product_brand_alter_product_durum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="durum",
            field=models.CharField(
                choices=[("Rent", "Rent"), ("satılık", "Sale")],
                max_length=50,
                null=True,
            ),
        ),
    ]
