# Generated by Django 5.0.3 on 2024-06-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0033_alter_product_durum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="durum",
            field=models.CharField(
                choices=[("Rent", "Rent"), ("Sale", "Sale")], max_length=50, null=True
            ),
        ),
    ]
