# Generated by Django 5.0.3 on 2024-06-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppEcommerce", "0035_alter_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                choices=[("Building", "Building"), ("Detached", "Detached")],
                max_length=50,
                null=True,
            ),
        ),
    ]
